name: /users/sgsrehm1/COMP702_BeyondAF/envs/openfold_env
channels:
  - pytorch
  - bioconda
  - nvidia
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - absl-py=2.4.0
  - annotated-types=0.7.0
  - aria2=1.37.0
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.7.0
  - aws-c-http=0.10.13
  - aws-c-io=0.26.3
  - aws-c-mqtt=0.15.2
  - aws-c-s3=0.12.2
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - awscli=2.35.11
  - awscrt=0.32.2
  - backports.zstd=1.6.0
  - binutils_impl_linux-64=2.45.1
  - biopython=1.87
  - blas=1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.6.17
  - certifi=2026.6.17
  - charset-normalizer=3.4.7
  - click=8.4.1
  - colorama=0.4.6
  - cpython=3.10.20
  - cuda=12.4.1
  - cuda-cccl=12.4.127
  - cuda-command-line-tools=12.4.1
  - cuda-compiler=12.6.2
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart-static=12.4.127
  - cuda-cuobjdump=12.4.127
  - cuda-cupti=12.4.127
  - cuda-cupti-static=12.4.127
  - cuda-cuxxfilt=12.4.127
  - cuda-demo-suite=12.4.127
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.4.127
  - cuda-gdb=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.6.0
  - cuda-libraries-static=12.4.1
  - cuda-nsight=12.4.127
  - cuda-nvcc=12.4.131
  - cuda-nvdisasm=12.4.127
  - cuda-nvml-dev=12.4.127
  - cuda-nvprof=12.4.127
  - cuda-nvprune=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvrtc-static=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvp=12.4.127
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.4.1
  - cuda-sanitizer-api=12.4.127
  - cuda-toolkit=12.4.1
  - cuda-tools=12.4.1
  - cuda-visual-tools=12.6.0
  - cudatoolkit=11.8.0
  - distro=1.8.0
  - docutils=0.19
  - filelock=3.29.4
  - gawk=5.4.0
  - gcc=12.4.0
  - gcc_impl_linux-64=12.4.0
  - gds-tools=1.9.1.3
  - git=2.54.0
  - gitdb=4.0.12
  - gitpython=3.1.50
  - gmp=6.3.0
  - gmpy2=2.3.0
  - gsl=2.7
  - h2=4.3.0
  - hhsuite=3.3.0
  - hmmer=3.4
  - hpack=4.2.0
  - hyperframe=6.1.0
  - icu=78.3
  - idna=3.18
  - ihm=2.11
  - jinja2=3.1.6
  - jmespath=1.0.1
  - kalign2=2.04
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.22.2
  - ld_impl_linux-64=2.45.1
  - legacy-cgi=2.6.4
  - libabseil=20260526.0
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcublas-static=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcufft-static=11.2.1.3
  - libcufile=1.9.1.3
  - libcufile-dev=1.9.1.3
  - libcufile-static=1.9.1.3
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurand-static=10.3.5.147
  - libcurl=8.21.0
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusolver-static=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libcusparse-static=12.3.1.170
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.8.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.13.0
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.3
  - libnghttp2=1.68.1
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnpp-static=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvfatbin-dev=12.4.127
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libnvjpeg-static=12.3.1.117
  - libsanitizer=12.4.0
  - libsqlite=3.53.3
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.42.2
  - libxcrypt=4.4.36
  - libxml2=2.15.3
  - libxml2-16=2.15.3
  - libzlib=1.3.2
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2023.2.0
  - ml-collections=1.0.0
  - mmseqs2=18.8cc5c
  - modelcif=0.7
  - mpc=1.4.0
  - mpfr=4.2.2
  - mpi=1.0
  - msgpack-python=1.2.1
  - ncurses=6.6
  - networkx=3.4.2
  - nsight-compute=2024.1.1.4
  - numpy=2.2.6
  - ocl-icd=2.3.4
  - ocl-icd-system=1.0.0
  - opencl-headers=2025.06.13
  - openmm=8.2.0
  - openmpi=4.1.6
  - openssl=3.6.3
  - packaging=26.2
  - pandas=2.3.3
  - pcre2=10.47
  - pdbfixer=1.12
  - perl=5.32.1
  - pip=26.1.2
  - platformdirs=4.10.0
  - prompt-toolkit=3.0.51
  - protobuf=7.35.1
  - pydantic=2.13.4
  - pydantic-core=2.46.4
  - pysocks=1.7.1
  - python=3.10.20
  - python-dateutil=2.9.0
  - python-tzdata=2026.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2026.2
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.34.2
  - ruamel.yaml=0.19.1
  - ruamel.yaml.clib=0.2.15
  - s2n=1.7.2
  - scipy=1.15.2
  - sentry-sdk=2.63.0
  - setuptools=59.5.0
  - six=1.17.0
  - smmap=5.0.3
  - sysroot_linux-64=2.34
  - tbb=2021.13.0
  - tk=8.6.13
  - torchtriton=3.1.0
  - tqdm=4.68.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wandb=0.28.0
  - wcwidth=0.2.14
  - wheel=0.47.0
  - yaml=0.2.5
  - zlib=1.3.2
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.2
      - aiohttp==3.14.1
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==26.1.0
      - backports-strenum==1.3.1
      - contourpy==1.3.2
      - cuda-python==12.4.0
      - cycler==0.12.1
      - dm-tree==0.1.10
      - fonttools==4.63.0
      - frozenlist==1.8.0
      - fsspec==2026.6.0
      - kiwisolver==1.5.0
      - lightning-utilities==0.15.3
      - matplotlib==3.10.9
      - mpmath==1.3.0
      - multidict==6.7.1
      - pillow==12.3.0
      - propcache==0.5.2
      - pyparsing==3.3.2
      - pytorch-lightning==1.9.5
      - sympy==1.13.1
      - torchmetrics==1.9.0
      - wrapt==2.2.2
      - yarl==1.24.2
variables:
  CUTLASS_PATH: /users/sgmwu14/openfold/cutlass
  KMP_AFFINITY: none
